<script>
	import SectionTitle from '$lib/components/SectionTitle.svelte';
	import LogoBlank from './art/LogoBlank.svelte';
</script>

<section class="u-container">
	<SectionTitle title="Explain" />

	<p><LogoBlank /> reset.css is based on Preflight from Tailwind CSS, a modern CSS reset.</p>
	<p>
		<LogoBlank />
		typography.css and spacing.css are responsive clamp-based values generated by
		<a href="https://utopia.fyi"> Utopia </a>
	</p>
</section>
